### ISSUE TITLE
[Bug] ไม่สามารถทดลองเล่นได้จากหน้าเว็บ

### ISSUE THREAD

**Issue by nitipatl** [matong1745/problem-vending-machine#1]
จากลิงค์นี้ครับ https://ending-machine-igeer-geek.firebaseapp.com/
ลองดูว่าแก้ไขได้ไหม และ ปัญหาเกิดจากอะไรได้บ้าง

**Comment by matong1745** [comment]
![image](https://user-images.githubusercontent.com/25519723/45596088-69953880-b9e0-11e8-85d7-aaaff766877d.png)
endpoint unsecured ครับผม
ทำให้ เรียก api นี้ไม่ได้
ปลดล๊อค authorized ใน axios ก็แก้ไขไม่ได้ครับ
วิธีแก้ชั่วคราวคือ
![image](https://user-images.githubusercontent.com/25519723/45596107-b416b500-b9e0-11e8-8a33-b1985edd9e68.png)
ให้กด Load unsafe scripts ครับ

**Comment by nitipatl** [comment]
มีวิธีแบบแก้ไขถาวรไหมครับ

สมมติลูกค้าอยากใช้งานจริง

**Comment by matong1745** [comment]
ในความคิดผมนะครับ ก็ไปแก้ให้ endpoint มัน secure ดีกว่ามานั่งปลดให้ frontend รันแบบ unsecured มันไม่น่าจะปลอดภัยนะครับ ถ้าแก้ไม่ได้จริงๆ ก็ แนะให้ไป mock json ใน frontend ไปเลยง่ายกว่า

**Comment by nitipatl** [comment]
อ่า แต่ api ของเราอยู่กับ mocky น่ะครับ พอจะมีทางไหมครับ

**Comment by matong1745** [comment]
แนะนำให้ใช้ postman ครับ
ผมทำไว้ละ 
https://d8400409-c45a-4cf2-b9cb-b0a81913f0c0.mock.pstmn.io/products

**Comment by matong1745** [comment]
ลอง test url เดิมได้นะครับ  https://ending-machine-igeer-geek.firebaseapp.com/
เวิคละครับ
